name: Daily News Report
on:
  schedule:
    # 每天台灣時間早上 8:10 執行 (UTC 0:10)
    - cron: '10 0 * * *'
  workflow_dispatch:  # 允許手動觸發測試

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Generate and send news report
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        HACKMD_TOKEN: ${{ secrets.HACKMD_TOKEN }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python main.py
    
    - name: Upload report as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: daily-report-${{ github.run_number }}
        path: reports/
        retention-days: 30
